### PR TITLE
Bump version to 6.1.0

### PR DESCRIPTION
**Pull request by nickhsine**
I am going to release 6.1.0 stable version.
Please help to check if anything missing.

@taylrj @YuCJ

### CODE REVIEW

**Comment by nickhsine** [comment]
@YuCJ 
Is this PR (https://github.com/twreporter/twreporter-react-components/pull/124/files) going to release in v6.1.0 stable version? 
If so, please help to merge that PR first. 
I would merge this PR after you.

**Comment by taylrj** [comment]
LGTM

**Comment by YuCJ** [comment]
The PR #124 has been merged

**Comment by nickhsine** [comment]
`@twreporter/react-components@6.1.0` has been released.

**Pull request merged**
